CREATE TABLE IF NOT EXISTS menu_items (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  name TEXT NOT NULL,
  category TEXT NOT NULL,
  price REAL NOT NULL,
  original_price REAL,
  is_veg INTEGER DEFAULT 0,
  description TEXT,
  image TEXT,
  is_available INTEGER DEFAULT 1,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP
);

INSERT INTO menu_items (id, name, category, price, original_price, is_veg, description, image, is_available) VALUES (1, 'Special Kashmiri Mutton Biryani', 'biryani-rice', 380, NULL, 0, 'Slow-cooked tender Kashmiri mutton layered with saffron basmati rice, aromatic spices, and fried onions.', './images/biryani.png', 1);
INSERT INTO menu_items (id, name, category, price, original_price, is_veg, description, image, is_available) VALUES (2, 'Ertugrul Royal Chicken Biryani', 'biryani-rice', 320, NULL, 0, 'Chef''s signature chicken biryani infused with saffron, cardamom, and roasted cashews.', './images/biryani.png', 1);
INSERT INTO menu_items (id, name, category, price, original_price, is_veg, description, image, is_available) VALUES (3, 'Tandoori Chicken Tikka Biryani', 'biryani-rice', 340, NULL, 0, 'Charcoal-grilled chicken tikka chunks dum-cooked with fragrant long-grain rice.', '', 1);
INSERT INTO menu_items (id, name, category, price, original_price, is_veg, description, image, is_available) VALUES (4, 'Kashmiri Wazwan Rista Biryani', 'biryani-rice', 420, NULL, 0, 'Authentic pounded meatball Rista cooked in saffron gravy and layered over royal basmati.', '', 1);
INSERT INTO menu_items (id, name, category, price, original_price, is_veg, description, image, is_available) VALUES (5, 'Hyderabadi Dum Mutton Biryani', 'biryani-rice', 390, NULL, 0, 'Spicy & flavorful layered mutton biryani prepared in traditional sealed handi.', '', 1);
INSERT INTO menu_items (id, name, category, price, original_price, is_veg, description, image, is_available) VALUES (6, 'Veg Saffron Pulao', 'biryani-rice', 220, NULL, 1, 'Fragrant basmati rice tossed with Kashmiri saffron, dry fruits, green peas, and ghee.', '', 1);
INSERT INTO menu_items (id, name, category, price, original_price, is_veg, description, image, is_available) VALUES (7, 'Paneer Tikka Dum Biryani', 'biryani-rice', 270, NULL, 1, 'Marinated cottage cheese cubes layered with caramelized onions and aromatic herbs.', '', 1);
INSERT INTO menu_items (id, name, category, price, original_price, is_veg, description, image, is_available) VALUES (8, 'Egg Dum Biryani', 'biryani-rice', 240, NULL, 0, 'Boiled fried eggs simmered in rich gravy layered with seasoned basmati rice.', '', 1);
INSERT INTO menu_items (id, name, category, price, original_price, is_veg, description, image, is_available) VALUES (9, 'Jeera Fried Rice', 'biryani-rice', 160, NULL, 1, 'Fluffy basmati rice tempered with roasted cumin seeds and fresh coriander.', '', 1);
INSERT INTO menu_items (id, name, category, price, original_price, is_veg, description, image, is_available) VALUES (10, 'Kashmiri Sweet Shahi Pulao', 'biryani-rice', 280, NULL, 1, 'Traditional sweet pulao loaded with almonds, walnuts, raisins, and aromatic spices.', '', 1);
INSERT INTO menu_items (id, name, category, price, original_price, is_veg, description, image, is_available) VALUES (11, 'Chicken Fried Rice', 'biryani-rice', 240, NULL, 0, 'Wok-tossed basmati rice with tender chicken strips, scrambled egg, and spring onions.', '', 1);
INSERT INTO menu_items (id, name, category, price, original_price, is_veg, description, image, is_available) VALUES (12, 'Steamed Basmati Rice', 'biryani-rice', 130, NULL, 1, 'Long-grain Himalayan basmati rice cooked to fluffy perfection.', '', 1);
INSERT INTO menu_items (id, name, category, price, original_price, is_veg, description, image, is_available) VALUES (13, 'Ertugrul Chicken Feast Pizza', 'non-veg-pizza', 450, NULL, 0, 'Loaded with grilled chicken tikka, spicy minced chicken, pepperoni, bell peppers, and mozzarella.', '', 1);
INSERT INTO menu_items (id, name, category, price, original_price, is_veg, description, image, is_available) VALUES (14, 'Chicken Tikka Supreme Pizza', 'non-veg-pizza', 390, NULL, 0, 'Smoky tandoori chicken, red onions, capsicum, and makhani drizzle on hand-tossed crust.', '', 1);
INSERT INTO menu_items (id, name, category, price, original_price, is_veg, description, image, is_available) VALUES (15, 'BBQ Smoked Chicken Pizza', 'non-veg-pizza', 410, NULL, 0, 'Tangy hickory BBQ sauce base topped with smoked chicken, jalapenos, and melted cheddar.', '', 1);
INSERT INTO menu_items (id, name, category, price, original_price, is_veg, description, image, is_available) VALUES (16, 'Kebab Special Pizza', 'non-veg-pizza', 440, NULL, 0, 'Authentic sliced mutton seekh kebab, green chilies, mint cream, and double mozzarella.', '', 1);
INSERT INTO menu_items (id, name, category, price, original_price, is_veg, description, image, is_available) VALUES (17, 'Spicy Peri-Peri Chicken Pizza', 'non-veg-pizza', 380, NULL, 0, 'Fiery peri-peri chicken chunks, spicy sauce, red paprika, and stretchy cheese.', '', 1);
INSERT INTO menu_items (id, name, category, price, original_price, is_veg, description, image, is_available) VALUES (18, 'Chicken Sausage & Pepperoni Pizza', 'non-veg-pizza', 420, NULL, 0, 'Classic Italian style crisp crust topped with chicken sausage, smoked pepperoni & oregano.', '', 1);
INSERT INTO menu_items (id, name, category, price, original_price, is_veg, description, image, is_available) VALUES (19, 'Classic Margherita Pizza', 'veg-pizza', 280, NULL, 1, 'Rich San Marzano tomato sauce, fresh basil leaves, extra virgin olive oil & double mozzarella.', '', 1);
INSERT INTO menu_items (id, name, category, price, original_price, is_veg, description, image, is_available) VALUES (20, 'Paneer Tikka Passion Pizza', 'veg-pizza', 350, NULL, 1, 'Marinated spiced paneer cubes, crisp capsicum, caramelized red onions & coriander.', '', 1);
INSERT INTO menu_items (id, name, category, price, original_price, is_veg, description, image, is_available) VALUES (21, 'Farmhouse Veggie Deluxe', 'veg-pizza', 340, NULL, 1, 'Black olives, crunchy bell peppers, sweet corn, mushrooms, red onion, and mozzarella.', '', 1);
INSERT INTO menu_items (id, name, category, price, original_price, is_veg, description, image, is_available) VALUES (22, 'Four Cheese Garden Feast', 'veg-pizza', 390, NULL, 1, 'Rich blend of Mozzarella, Cheddar, Processed Cheese & Parmesan with garlic butter crust.', '', 1);
INSERT INTO menu_items (id, name, category, price, original_price, is_veg, description, image, is_available) VALUES (23, 'Spicy Jalapeno & Mushroom Pizza', 'veg-pizza', 330, NULL, 1, 'Sauteed button mushrooms, pickled jalapenos, paprika flakes, and spicy tomato glaze.', '', 1);
INSERT INTO menu_items (id, name, category, price, original_price, is_veg, description, image, is_available) VALUES (24, 'Mexican Veggie Volcano', 'veg-pizza', 360, NULL, 1, 'Sweet corn, black beans, salsa drizzle, capsicum, green chillies & melted cheese.', '', 1);
INSERT INTO menu_items (id, name, category, price, original_price, is_veg, description, image, is_available) VALUES (25, 'Corn & Cheese Delight', 'veg-pizza', 290, NULL, 1, 'Golden juicy sweet corn paired with liquid cheese sauce and mozzarella base.', '', 1);
INSERT INTO menu_items (id, name, category, price, original_price, is_veg, description, image, is_available) VALUES (26, 'Kashmiri Herb & Cheese Special', 'veg-pizza', 320, NULL, 1, 'Infused with local Kashmiri herbs, roasted garlic, sun-dried tomatoes, and cheese.', '', 1);
INSERT INTO menu_items (id, name, category, price, original_price, is_veg, description, image, is_available) VALUES (27, 'Full Tandoori Chicken Grill', 'house-of-tandoor', 520, NULL, 0, 'Whole chicken marinated overnight in yogurt & royal tandoori spices, charcoal roasted.', './images/kebabs.png', 1);
INSERT INTO menu_items (id, name, category, price, original_price, is_veg, description, image, is_available) VALUES (28, 'Half Tandoori Chicken Grill', 'house-of-tandoor', 290, NULL, 0, 'Half charcoal roasted chicken infused with Kashmiri red chili and lemon.', './images/kebabs.png', 1);
INSERT INTO menu_items (id, name, category, price, original_price, is_veg, description, image, is_available) VALUES (29, 'Afghani Malai Tandoori Chicken', 'house-of-tandoor', 360, NULL, 0, 'Succulent chicken leg & breast pieces steeped in rich cashew cream and green cardamom.', '', 1);
INSERT INTO menu_items (id, name, category, price, original_price, is_veg, description, image, is_available) VALUES (30, 'Steamed Chicken Momos (8 Pcs)', 'momo-hut', 180, NULL, 0, 'Juicy minced chicken steamed in paper-thin dumplings served with fiery garlic chili dip.', '', 1);
INSERT INTO menu_items (id, name, category, price, original_price, is_veg, description, image, is_available) VALUES (31, 'Kurkure Fried Chicken Momos (8 Pcs)', 'momo-hut', 220, NULL, 0, 'Crispy outer cornflake crust filled with tender seasoned chicken filling.', '', 1);
INSERT INTO menu_items (id, name, category, price, original_price, is_veg, description, image, is_available) VALUES (32, 'Steamed Veg Paneer Momos (8 Pcs)', 'momo-hut', 160, NULL, 1, 'Soft dumplings packed with spiced grated paneer, cabbage, and spring herbs.', '', 1);
INSERT INTO menu_items (id, name, category, price, original_price, is_veg, description, image, is_available) VALUES (33, 'Tandoori Gravy Momos (8 Pcs)', 'momo-hut', 240, NULL, 0, 'Charcoal-tossed momos slathered in rich creamy makhani gravy and chat masala.', '', 1);
INSERT INTO menu_items (id, name, category, price, original_price, is_veg, description, image, is_available) VALUES (34, 'Chili Schezwan Veg Momos (8 Pcs)', 'momo-hut', 190, NULL, 1, 'Pan-fried veg momos tossed in spicy Schezwan sauce, peppers, and onions.', '', 1);
INSERT INTO menu_items (id, name, category, price, original_price, is_veg, description, image, is_available) VALUES (35, 'Butter Chicken Special', 'main-course-non-veg', 380, NULL, 0, 'Tender tandoori chicken pieces simmered in rich creamy tomato and butter gravy.', '', 1);
INSERT INTO menu_items (id, name, category, price, original_price, is_veg, description, image, is_available) VALUES (36, 'Kashmiri Mutton Rogan Josh', 'main-course-non-veg', 440, NULL, 0, 'Signature Kashmiri mutton curry stewed with alkanet root, fennel, and aromatic spices.', '', 1);
INSERT INTO menu_items (id, name, category, price, original_price, is_veg, description, image, is_available) VALUES (37, 'Kashmiri Chicken Kanti Gravy', 'main-course-non-veg', 360, NULL, 0, 'Pan-seared spiced chicken pieces cooked with onions, tomatoes, and local spices.', '', 1);
INSERT INTO menu_items (id, name, category, price, original_price, is_veg, description, image, is_available) VALUES (38, 'Kadai Chicken Peshawari', 'main-course-non-veg', 350, NULL, 0, 'Chicken braised in coarse spice powder, capsicum, and thick tomato onion masala.', '', 1);
INSERT INTO menu_items (id, name, category, price, original_price, is_veg, description, image, is_available) VALUES (39, 'Chicken Korma Shahi', 'main-course-non-veg', 370, NULL, 0, 'Royal white gravy made from almond cashew paste, cream, and tender chicken.', '', 1);
INSERT INTO menu_items (id, name, category, price, original_price, is_veg, description, image, is_available) VALUES (40, 'Mutton Wazwan Gushtaba', 'main-course-non-veg', 460, NULL, 0, 'Pounded mutton meatballs cooked in flavorful spiced yogurt gravy.', '', 1);
INSERT INTO menu_items (id, name, category, price, original_price, is_veg, description, image, is_available) VALUES (41, 'Chicken Tikka Masala', 'main-course-non-veg', 370, NULL, 0, 'Smoky chicken tikka chunks tossed in spicy medium thick onion-tomato gravy.', '', 1);
INSERT INTO menu_items (id, name, category, price, original_price, is_veg, description, image, is_available) VALUES (42, 'Mutton Bhuna Gosht', 'main-course-non-veg', 430, NULL, 0, 'Slow-roasted mutton cooked with whole spices until dark and intensely flavorful.', '', 1);
INSERT INTO menu_items (id, name, category, price, original_price, is_veg, description, image, is_available) VALUES (43, 'Egg Curry Special', 'main-course-non-veg', 240, NULL, 0, 'Boiled golden fried eggs simmered in rich gravy with green chili coriander garnishing.', '', 1);
INSERT INTO menu_items (id, name, category, price, original_price, is_veg, description, image, is_available) VALUES (44, 'Paneer Butter Masala', 'main-course-veg', 310, NULL, 1, 'Fresh cottage cheese cubes in silky smooth tomato, butter, and cashew cream gravy.', '', 1);
INSERT INTO menu_items (id, name, category, price, original_price, is_veg, description, image, is_available) VALUES (45, 'Kadai Paneer Royal', 'main-course-veg', 300, NULL, 1, 'Cottage cheese tossed with crushed spices, capsicum, and diced onions.', '', 1);
INSERT INTO menu_items (id, name, category, price, original_price, is_veg, description, image, is_available) VALUES (46, 'Dal Makhani Shahi', 'main-course-veg', 270, NULL, 1, 'Overnight slow-cooked black lentils enriched with butter, cream, and aromatic herbs.', '', 1);
INSERT INTO menu_items (id, name, category, price, original_price, is_veg, description, image, is_available) VALUES (47, 'Kashmiri Dum Aloo', 'main-course-veg', 250, NULL, 1, 'Baby potatoes deep fried and simmered in spicy Kashmiri red chili fennel yogurt gravy.', '', 1);
INSERT INTO menu_items (id, name, category, price, original_price, is_veg, description, image, is_available) VALUES (48, 'Malai Kofta Sweet Gravy', 'main-course-veg', 320, NULL, 1, 'Soft paneer & potato dumplings served in velvety golden cashew gravy.', '', 1);
INSERT INTO menu_items (id, name, category, price, original_price, is_veg, description, image, is_available) VALUES (49, 'Mix Vegetable Jalfrzi', 'main-course-veg', 240, NULL, 1, 'Assorted garden veggies stir-fried with sweet peppers and tang spice blend.', '', 1);
INSERT INTO menu_items (id, name, category, price, original_price, is_veg, description, image, is_available) VALUES (50, 'Yellow Dal Tadka', 'main-course-veg', 210, NULL, 1, 'Arhar dal tempered with ghee, cumin seeds, garlic, and fresh green chilies.', '', 1);
INSERT INTO menu_items (id, name, category, price, original_price, is_veg, description, image, is_available) VALUES (51, 'Palak Paneer Special', 'main-course-veg', 290, NULL, 1, 'Blanched spinach puree seasoned with garlic and soft fresh paneer cubes.', '', 1);
INSERT INTO menu_items (id, name, category, price, original_price, is_veg, description, image, is_available) VALUES (52, 'Authentic Kashmiri Mutton Kanti', 'kanti-kebab', 420, NULL, 0, 'Boneless mutton pieces pan-fried with onions, tomatoes, green chillies & local spices.', './images/kebabs.png', 1);
INSERT INTO menu_items (id, name, category, price, original_price, is_veg, description, image, is_available) VALUES (53, 'Srinagar Special Chicken Kanti', 'kanti-kebab', 340, NULL, 0, 'Sizzling boneless chicken stir-fried with bell peppers, chili oil, and fresh herbs.', './images/kebabs.png', 1);
INSERT INTO menu_items (id, name, category, price, original_price, is_veg, description, image, is_available) VALUES (54, 'Tandoori Mutton Seekh Kebab (4 Pcs)', 'kanti-kebab', 390, NULL, 0, 'Minced mutton skewers seasoned with royal spices and cooked over white hot coals.', './images/kebabs.png', 1);
INSERT INTO menu_items (id, name, category, price, original_price, is_veg, description, image, is_available) VALUES (55, 'Chicken Malai Reshmi Kebab (4 Pcs)', 'kanti-kebab', 350, NULL, 0, 'Melt-in-mouth chicken skewers marinated in cream, cheese, and white pepper.', '', 1);
INSERT INTO menu_items (id, name, category, price, original_price, is_veg, description, image, is_available) VALUES (56, 'Ertugrul Special Chicken Tikka Roll', 'kathi-rolls', 190, NULL, 0, 'Flaky paratha stuffed with spicy chicken tikka, sliced onions, and mint mayo.', '', 1);
INSERT INTO menu_items (id, name, category, price, original_price, is_veg, description, image, is_available) VALUES (57, 'Mutton Seekh Kebab Roll', 'kathi-rolls', 230, NULL, 0, 'Smoky mutton seekh kebab wrapped with egg paratha, chutney, and spicy salad.', '', 1);
INSERT INTO menu_items (id, name, category, price, original_price, is_veg, description, image, is_available) VALUES (58, 'Paneer Tikka Roll', 'kathi-rolls', 160, NULL, 1, 'Soft roomali wrap loaded with grilled paneer, peppers, garlic sauce, and chat spices.', '', 1);
INSERT INTO menu_items (id, name, category, price, original_price, is_veg, description, image, is_available) VALUES (59, 'Kashmiri Saffron Almond Shake', 'mocktails-shakes', 220, NULL, 1, 'Pure saffron infused cold milk blended with soaked almonds, pistachio & ice cream.', './images/drinks.png', 1);
INSERT INTO menu_items (id, name, category, price, original_price, is_veg, description, image, is_available) VALUES (60, 'Ertugrul Blue Lagoon Mocktail', 'mocktails-shakes', 180, NULL, 1, 'Refreshing blue curaçao, lemon juice, mint leaves, and sparkling sprite.', './images/drinks.png', 1);
INSERT INTO menu_items (id, name, category, price, original_price, is_veg, description, image, is_available) VALUES (61, 'Virgin Mint Mojito', 'mocktails-shakes', 160, NULL, 1, 'Muddled fresh mint leaves, lime juice, brown sugar, and soda water.', '', 1);
INSERT INTO menu_items (id, name, category, price, original_price, is_veg, description, image, is_available) VALUES (62, 'Belgian Chocolate Overload Shake', 'mocktails-shakes', 210, NULL, 1, 'Thick chocolate milk blend topped with whipped cream, chocochips, and chocolate drizzle.', '', 1);
INSERT INTO menu_items (id, name, category, price, original_price, is_veg, description, image, is_available) VALUES (63, 'Strawberry Cream Delight Shake', 'mocktails-shakes', 190, NULL, 1, 'Real strawberry crush whipped with cold milk and vanilla ice cream scoop.', '', 1);
INSERT INTO menu_items (id, name, category, price, original_price, is_veg, description, image, is_available) VALUES (64, 'Watermelon Mint Cooler', 'mocktails-shakes', 170, NULL, 1, 'Freshly pressed watermelon juice topped with black salt and crushed ice.', '', 1);
INSERT INTO menu_items (id, name, category, price, original_price, is_veg, description, image, is_available) VALUES (65, 'Oreo Brownie Thickshake', 'mocktails-shakes', 220, NULL, 1, 'Crumbled Oreo cookies and chocolate brownie blended to thick perfection.', '', 1);
INSERT INTO menu_items (id, name, category, price, original_price, is_veg, description, image, is_available) VALUES (66, 'Crispy Peri-Peri French Fries', 'snacks-light-munchies', 140, NULL, 1, 'Golden fried potato fries tossed in fiery African peri-peri seasoning.', '', 1);
INSERT INTO menu_items (id, name, category, price, original_price, is_veg, description, image, is_available) VALUES (67, 'Cheesy Loaded Nachos', 'snacks-light-munchies', 190, NULL, 1, 'Crisp tortilla chips baked with warm jalapeno cheese sauce, salsa, and olives.', '', 1);
INSERT INTO menu_items (id, name, category, price, original_price, is_veg, description, image, is_available) VALUES (68, 'Chicken Nuggets (8 Pcs)', 'snacks-light-munchies', 210, NULL, 0, 'Crispy golden breaded chicken bite-sized nuggets with cocktail dip.', '', 1);
INSERT INTO menu_items (id, name, category, price, original_price, is_veg, description, image, is_available) VALUES (69, 'Cheese Garlic Bread Sticks', 'snacks-light-munchies', 170, NULL, 1, 'Freshly baked bread toasted with garlic butter and pull-apart mozzarella.', '', 1);
INSERT INTO menu_items (id, name, category, price, original_price, is_veg, description, image, is_available) VALUES (70, 'Crispy Fried Chicken Wings (6 Pcs)', 'snacks-light-munchies', 260, NULL, 0, 'Juicy chicken wings coated in crunchy batter and spicy BBQ dip.', '', 1);
INSERT INTO menu_items (id, name, category, price, original_price, is_veg, description, image, is_available) VALUES (71, 'Veg Cheese Finger Crisp', 'snacks-light-munchies', 160, NULL, 1, 'Deep-fried cheese and potato fingers served hot with chili dip.', '', 1);
INSERT INTO menu_items (id, name, category, price, original_price, is_veg, description, image, is_available) VALUES (72, 'Chicken Lollipop (6 Pcs)', 'snacks-light-munchies', 270, NULL, 0, 'Frenched chicken winglets marinated in hot Indo-Chinese spices.', '', 1);
INSERT INTO menu_items (id, name, category, price, original_price, is_veg, description, image, is_available) VALUES (73, 'Corn & Cheese Balls (8 Pcs)', 'snacks-light-munchies', 180, NULL, 1, 'Melted cheese and sweet corn balls encased in a crunchy breadcrumb coating.', '', 1);
INSERT INTO menu_items (id, name, category, price, original_price, is_veg, description, image, is_available) VALUES (74, 'Chicken Hakka Noodles', 'noodles', 230, NULL, 0, 'Stir-fried wheat noodles tossed with shredded chicken, peppers, and garlic soy glaze.', '', 1);
INSERT INTO menu_items (id, name, category, price, original_price, is_veg, description, image, is_available) VALUES (75, 'Veg Schezwan Noodles', 'noodles', 190, NULL, 1, 'Spicy wok-tossed noodles packed with colorful vegetables and hot Schezwan paste.', '', 1);
INSERT INTO menu_items (id, name, category, price, original_price, is_veg, description, image, is_available) VALUES (76, 'Egg Chili Garlic Noodles', 'noodles', 210, NULL, 0, 'Noodles fried with scrambled eggs, burnt garlic, green chilies, and scallions.', '', 1);
INSERT INTO menu_items (id, name, category, price, original_price, is_veg, description, image, is_available) VALUES (77, 'Ertugrul Special Mix Noodles', 'noodles', 260, NULL, 0, 'Combination of chicken, egg, and fresh veggies wok-tossed in signature Oriental sauce.', '', 1);
INSERT INTO menu_items (id, name, category, price, original_price, is_veg, description, image, is_available) VALUES (78, 'Fresh Green Garden Salad', 'salad', 120, NULL, 1, 'Sliced cucumbers, tomatoes, carrots, onions, lemon wedges, and green chilies.', '', 1);
INSERT INTO menu_items (id, name, category, price, original_price, is_veg, description, image, is_available) VALUES (79, 'Grilled Chicken Caesar Salad', 'salad', 220, NULL, 0, 'Crisp iceberg lettuce, grilled chicken breast, garlic croutons, and Caesar dressing.', '', 1);
INSERT INTO menu_items (id, name, category, price, original_price, is_veg, description, image, is_available) VALUES (80, 'Butter Garlic Naan', 'bread-naan', 70, NULL, 1, 'Tandoor baked unleavened bread topped with minced garlic and melted butter.', '', 1);
INSERT INTO menu_items (id, name, category, price, original_price, is_veg, description, image, is_available) VALUES (81, 'Butter Naan Shahi', 'bread-naan', 60, NULL, 1, 'Soft tandoor baked bread brushed generously with pure butter.', '', 1);
INSERT INTO menu_items (id, name, category, price, original_price, is_veg, description, image, is_available) VALUES (82, 'Cheese Stuffed Naan', 'bread-naan', 110, NULL, 1, 'Refined flour dough stuffed with seasoned gooey mozzarella and spices.', '', 1);
INSERT INTO menu_items (id, name, category, price, original_price, is_veg, description, image, is_available) VALUES (83, 'Tandoori Roti Butter', 'bread-naan', 30, NULL, 1, 'Whole wheat bread baked in clay tandoor smeared with fresh butter.', '', 1);
INSERT INTO menu_items (id, name, category, price, original_price, is_veg, description, image, is_available) VALUES (84, 'Creamy Chicken Alfredo Penne', 'pasta', 290, NULL, 0, 'Penne pasta tossed in rich white parmesan cheese sauce with grilled chicken strips.', '', 1);
INSERT INTO menu_items (id, name, category, price, original_price, is_veg, description, image, is_available) VALUES (85, 'Spicy Arrabbiata Veg Pasta', 'pasta', 240, NULL, 1, 'Penne pasta tossed in spicy Italian tomato sauce with crushed chili and black olives.', '', 1);
INSERT INTO menu_items (id, name, category, price, original_price, is_veg, description, image, is_available) VALUES (86, 'Ertugrul Royal Feast Combo (Save 30%)', 'combos', 665, 950, 0, 'Includes: 1 Special Kashmiri Mutton Biryani + 1 Half Tandoori Chicken + 2 Butter Naan + 2 Coke.', './images/biryani.png', 1);
INSERT INTO menu_items (id, name, category, price, original_price, is_veg, description, image, is_available) VALUES (87, 'Mutton Kanti & Biryani Mega Combo (Save 30%)', 'combos', 615, 880, 0, 'Includes: 1 Authentic Kashmiri Mutton Kanti + 1 Ertugrul Chicken Biryani + 2 Butter Garlic Naan.', './images/kebabs.png', 1);
INSERT INTO menu_items (id, name, category, price, original_price, is_veg, description, image, is_available) VALUES (88, 'Non-Veg Pizza Party Combo (Save 25%)', 'combos', 645, 860, 0, 'Includes: 1 Ertugrul Chicken Feast Pizza + 1 Crispy Fried Wings (6 Pcs) + 2 Virgin Mojitos.', '', 1);
INSERT INTO menu_items (id, name, category, price, original_price, is_veg, description, image, is_available) VALUES (89, 'Veg Butter Masala Family Combo (Save 30%)', 'combos', 504, 720, 1, 'Includes: 1 Paneer Butter Masala + 1 Dal Makhani + 4 Butter Naan + 1 Jeera Rice.', '', 1);
INSERT INTO menu_items (id, name, category, price, original_price, is_veg, description, image, is_available) VALUES (90, 'Kathi Roll & Shake Duo Combo (Save 25%)', 'combos', 307, 410, 0, 'Includes: 1 Ertugrul Special Chicken Roll + 1 Belgian Chocolate Overload Shake.', '', 1);
INSERT INTO menu_items (id, name, category, price, original_price, is_veg, description, image, is_available) VALUES (91, 'Momo & Noodle Street Combo (Save 25%)', 'combos', 307, 410, 0, 'Includes: 1 Kurkure Fried Chicken Momos (8 Pcs) + 1 Chicken Hakka Noodles + 1 Lemonade.', '', 1);
